# Use official lightweight Python image as the base
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /usr/src/app

# Install system dependencies required for Python packages and supervisor
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY .env .
COPY ../draft/scr_v2 .
COPY requirements.txt .

# Install Python dependencies
RUN uv pip install --system --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]