version: "3.9"

services:
  flask_test:
    build:
      context: ..
      dockerfile: ./Docker/dockerfile.flask_test
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    # volumes:
    #   - ./draft/scr_v2:/usr/src/app
    restart: unless-stopped

  streamlit_test:
    build:
      context: ..
      dockerfile: ./Docker/dockerfile.streamlit_test
    env_file:
      - ../.env
    ports:
      - "8501:8501"
    # volumes:
    #   - ./draft/scr_v2:/usr/src/app
    restart: unless-stopped

#############
# Version 2 #
#############
# version: "3.8"

# services:
#   flask:
#     image:
#       691831409651.dkr.ecr.ap-southeast-1.amazonaws.com/tg_bot:flask-app
#     restart: always
#     ports:
#       - "5000:5000"

#   streamlit:
#     image:
#       691831409651.dkr.ecr.ap-southeast-1.amazonaws.com/tg_bot:streamlit-app
#     restart: always
#     depends_on:
#       - flask
#     ports:
#       - "8501:8501"